"""add suggested_artist and suggested_title to staged_genres

Revision ID: 93ccb6e1d378
Revises: 57e31692de2b
Create Date: 2026-04-06 22:45:41.658595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ccb6e1d378'
down_revision: Union[str, Sequence[str], None] = '57e31692de2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staged_genres', sa.Column('suggested_artist', sa.String(), nullable=True))
    op.add_column('staged_genres', sa.Column('suggested_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staged_genres', 'suggested_title')
    op.drop_column('staged_genres', 'suggested_artist')
    # ### end Alembic commands ###
