"""remove suggested_artist and suggested_title from staged_genres

Revision ID: ae784ec4380e
Revises: 93ccb6e1d378
Create Date: 2026-04-06 22:54:49.774074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae784ec4380e'
down_revision: Union[str, Sequence[str], None] = '93ccb6e1d378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staged_genres', 'suggested_title')
    op.drop_column('staged_genres', 'suggested_artist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staged_genres', sa.Column('suggested_artist', sa.VARCHAR(), nullable=True))
    op.add_column('staged_genres', sa.Column('suggested_title', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
